// <auto-generated />
using System;
using MassageHuis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MassageHuis.Domains.Migrations
{
    [DbContext(typeof(MassageHuisDbContext))]
    [Migration("20250527170635_UpdateRegulierTijdslotCascadeDelete")]
    partial class UpdateRegulierTijdslotCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("GeboorteDatum")
                        .HasColumnType("date");

                    b.Property<string>("Geslacht")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Voornaam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MassageHuis.Entities.Betaling", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasComment("UUID");

                    b.Property<float>("BetaaldBedrag")
                        .HasColumnType("real");

                    b.Property<string>("Betaalmethode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("DatumBetaling")
                        .HasColumnType("date");

                    b.Property<int>("IdReservaties")
                        .HasColumnType("int")
                        .HasColumnName("Id_Reservaties");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TransactieReferentie")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Betaling__3214EC077816066A");

                    b.HasIndex("IdReservaties");

                    b.ToTable("Betaling", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.KostPrijs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTypeMassage")
                        .HasColumnType("int")
                        .HasColumnName("Id_TypeMassage");

                    b.Property<float>("Prijs")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Startdatum")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Prijs__3214EC07411AC5FA");

                    b.HasIndex("IdTypeMassage");

                    b.ToTable("KostPrijs");
                });

            modelBuilder.Entity("MassageHuis.Entities.Masseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("Einddienstverband")
                        .HasColumnType("date");

                    b.Property<string>("IdAspNetUsers")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_AspNetUsers");

                    b.HasKey("Id")
                        .HasName("PK__Masseur__3214EC07D33499EF");

                    b.HasIndex("IdAspNetUsers");

                    b.ToTable("Masseur", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.MasseurTypeMassage", b =>
                {
                    b.Property<int>("IdMasseur")
                        .HasColumnType("int")
                        .HasColumnName("Id_Masseur");

                    b.Property<int>("IdTypeMassage")
                        .HasColumnType("int")
                        .HasColumnName("Id_TypeMassage");

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int?>("Column")
                        .HasColumnType("int");

                    b.HasKey("IdMasseur", "IdTypeMassage")
                        .HasName("PK__Masseur___80E85080449674C6");

                    b.HasIndex("IdTypeMassage");

                    b.ToTable("Masseur_TypeMassage", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.PromotieCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Bedrag")
                        .HasColumnType("real");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdAspNetUsers")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_AspNetUsers");

                    b.Property<float?>("ResterendWaarde")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Vervaldatum")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Promotie__3214EC074E2CCBFC");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex(new[] { "Code" }, "UQ__Promotie__A25C5AA72EB1EDE9")
                        .IsUnique();

                    b.ToTable("PromotieCode", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.RegulierTijdslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dag")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EindTijd")
                        .HasColumnType("time");

                    b.Property<int>("IdSchema")
                        .HasColumnType("int")
                        .HasColumnName("Id_Schema");

                    b.Property<TimeOnly>("StartTijd")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Regulier__3214EC0771C1235F");

                    b.HasIndex("IdSchema");

                    b.ToTable("RegulierTijdslot", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumCreatie")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DatumReservatie")
                        .HasColumnType("datetime");

                    b.Property<string>("IdAspNetUsers")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id_AspNetUsers");

                    b.Property<int>("IdMasseur")
                        .HasColumnType("int")
                        .HasColumnName("Id_Masseur");

                    b.Property<int>("IdPrijs")
                        .HasColumnType("int")
                        .HasColumnName("Id_Prijs");

                    b.Property<string>("IdPromotieCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id_PromotieCode");

                    b.Property<int>("IdRegulierTijdslot")
                        .HasColumnType("int")
                        .HasColumnName("Id_RegulierTijdslot");

                    b.Property<int>("IdTypeMassage")
                        .HasColumnType("int")
                        .HasColumnName("Id_TypeMassage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<float>("TeBetalenBedrag")
                        .HasColumnType("real");

                    b.HasKey("Id")
                        .HasName("PK__Reservat__3214EC070AE0EE6F");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex("IdMasseur");

                    b.HasIndex("IdPrijs");

                    b.HasIndex("IdPromotieCode");

                    b.HasIndex("IdRegulierTijdslot");

                    b.HasIndex("IdTypeMassage");

                    b.ToTable("Reservaties");
                });

            modelBuilder.Entity("MassageHuis.Entities.ReservatiePromotieCode", b =>
                {
                    b.Property<int>("IdReservaties")
                        .HasColumnType("int")
                        .HasColumnName("Id_Reservaties");

                    b.Property<string>("IdPromotieCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id_PromotieCode");

                    b.Property<DateOnly>("DatumToepassing")
                        .HasColumnType("date");

                    b.HasKey("IdReservaties", "IdPromotieCode")
                        .HasName("PK__Reservat__4AA863BE68267C6D");

                    b.HasIndex("IdPromotieCode");

                    b.ToTable("Reservatie_PromotieCode", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.Schema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EindDatum")
                        .HasColumnType("date");

                    b.Property<int>("IdMasseur")
                        .HasColumnType("int")
                        .HasColumnName("Id_Masseur");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("StartDatum")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Schema__3214EC07A0AD3C59");

                    b.HasIndex("IdMasseur");

                    b.ToTable("Schema", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.TypeMassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__TypeMass__3214EC07EC691C22");

                    b.ToTable("TypeMassage", (string)null);
                });

            modelBuilder.Entity("MassageHuis.Entities.UitzonderingTijdslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Eindtijd")
                        .HasColumnType("time");

                    b.Property<int>("IdSchema")
                        .HasColumnType("int")
                        .HasColumnName("Id_Schema");

                    b.Property<TimeOnly>("Startijd")
                        .HasColumnType("time");

                    b.Property<string>("TypeUitzondering")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Uitzonde__3214EC07D33295B0");

                    b.HasIndex("IdSchema");

                    b.ToTable("UitzonderingTijdslot", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MassageHuis.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetRoleClaim", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserClaim", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserLogin", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUserToken", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MassageHuis.Entities.Betaling", b =>
                {
                    b.HasOne("MassageHuis.Entities.Reservatie", "IdReservatiesNavigation")
                        .WithMany("Betalingen")
                        .HasForeignKey("IdReservaties")
                        .IsRequired()
                        .HasConstraintName("FKBetaling230728");

                    b.Navigation("IdReservatiesNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.KostPrijs", b =>
                {
                    b.HasOne("MassageHuis.Entities.TypeMassage", "IdTypeMassageNavigation")
                        .WithMany("KostPrijs")
                        .HasForeignKey("IdTypeMassage")
                        .IsRequired()
                        .HasConstraintName("FKPrijs356693");

                    b.Navigation("IdTypeMassageNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.Masseur", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "IdAspNetUsersNavigation")
                        .WithMany("Masseurs")
                        .HasForeignKey("IdAspNetUsers")
                        .HasConstraintName("FK_Masseur_AspNetUsers");

                    b.Navigation("IdAspNetUsersNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.MasseurTypeMassage", b =>
                {
                    b.HasOne("MassageHuis.Entities.Masseur", "IdMasseurNavigation")
                        .WithMany("MasseurTypeMassages")
                        .HasForeignKey("IdMasseur")
                        .IsRequired()
                        .HasConstraintName("FKMasseur_Ty373364");

                    b.HasOne("MassageHuis.Entities.TypeMassage", "IdTypeMassageNavigation")
                        .WithMany("MasseurTypeMassages")
                        .HasForeignKey("IdTypeMassage")
                        .IsRequired()
                        .HasConstraintName("FKMasseur_Ty870180");

                    b.Navigation("IdMasseurNavigation");

                    b.Navigation("IdTypeMassageNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.PromotieCode", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "IdAspNetUsersNavigation")
                        .WithMany("PromotieCodes")
                        .HasForeignKey("IdAspNetUsers")
                        .HasConstraintName("FK_PromotieCode_AspNetUsers");

                    b.Navigation("IdAspNetUsersNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.RegulierTijdslot", b =>
                {
                    b.HasOne("MassageHuis.Entities.Schema", "IdSchemaNavigation")
                        .WithMany("RegulierTijdslots")
                        .HasForeignKey("IdSchema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FKRegulierTi511075");

                    b.Navigation("IdSchemaNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.Reservatie", b =>
                {
                    b.HasOne("MassageHuis.Entities.AspNetUser", "IdAspNetUsersNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdAspNetUsers")
                        .HasConstraintName("FK_Reservaties_AspNetUsers");

                    b.HasOne("MassageHuis.Entities.Masseur", "IdMasseurNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdMasseur")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__Id_Ma__160F4887");

                    b.HasOne("MassageHuis.Entities.KostPrijs", "IdPrijsNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdPrijs")
                        .IsRequired()
                        .HasConstraintName("FKReservatie487046");

                    b.HasOne("MassageHuis.Entities.PromotieCode", "IdPromotieCodeNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdPromotieCode")
                        .HasConstraintName("FKReservatie307222");

                    b.HasOne("MassageHuis.Entities.RegulierTijdslot", "IdRegulierTijdslotNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdRegulierTijdslot")
                        .IsRequired()
                        .HasConstraintName("FKReservatie515549");

                    b.HasOne("MassageHuis.Entities.TypeMassage", "IdTypeMassageNavigation")
                        .WithMany("Reservaties")
                        .HasForeignKey("IdTypeMassage")
                        .IsRequired()
                        .HasConstraintName("FKReservatie952270");

                    b.Navigation("IdAspNetUsersNavigation");

                    b.Navigation("IdMasseurNavigation");

                    b.Navigation("IdPrijsNavigation");

                    b.Navigation("IdPromotieCodeNavigation");

                    b.Navigation("IdRegulierTijdslotNavigation");

                    b.Navigation("IdTypeMassageNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.ReservatiePromotieCode", b =>
                {
                    b.HasOne("MassageHuis.Entities.PromotieCode", "IdPromotieCodeNavigation")
                        .WithMany("ReservatiePromotieCodes")
                        .HasForeignKey("IdPromotieCode")
                        .IsRequired()
                        .HasConstraintName("FKReservatie795620");

                    b.Navigation("IdPromotieCodeNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.Schema", b =>
                {
                    b.HasOne("MassageHuis.Entities.Masseur", "IdMasseurNavigation")
                        .WithMany("Schemas")
                        .HasForeignKey("IdMasseur")
                        .IsRequired()
                        .HasConstraintName("FKSchema133092");

                    b.Navigation("IdMasseurNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.UitzonderingTijdslot", b =>
                {
                    b.HasOne("MassageHuis.Entities.Schema", "IdSchemaNavigation")
                        .WithMany("UitzonderingTijdslots")
                        .HasForeignKey("IdSchema")
                        .IsRequired()
                        .HasConstraintName("FKUitzonderi594035");

                    b.Navigation("IdSchemaNavigation");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("MassageHuis.Entities.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("Masseurs");

                    b.Navigation("PromotieCodes");

                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MassageHuis.Entities.KostPrijs", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MassageHuis.Entities.Masseur", b =>
                {
                    b.Navigation("MasseurTypeMassages");

                    b.Navigation("Reservaties");

                    b.Navigation("Schemas");
                });

            modelBuilder.Entity("MassageHuis.Entities.PromotieCode", b =>
                {
                    b.Navigation("ReservatiePromotieCodes");

                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MassageHuis.Entities.RegulierTijdslot", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MassageHuis.Entities.Reservatie", b =>
                {
                    b.Navigation("Betalingen");
                });

            modelBuilder.Entity("MassageHuis.Entities.Schema", b =>
                {
                    b.Navigation("RegulierTijdslots");

                    b.Navigation("UitzonderingTijdslots");
                });

            modelBuilder.Entity("MassageHuis.Entities.TypeMassage", b =>
                {
                    b.Navigation("KostPrijs");

                    b.Navigation("MasseurTypeMassages");

                    b.Navigation("Reservaties");
                });
#pragma warning restore 612, 618
        }
    }
}
